services:

  # postgres:
  #   image: postgres:13
  #   container_name: database
  #   environment:
  #     POSTGRES_DB: ${DB_NAME}
  #     POSTGRES_USER: ${DB_USER}
  #     POSTGRES_PASSWORD: ${DB_PASS}
  #   ports:
  #     - "${DB_PORT}:5432"
  #   env_file:
  #     - .env
  #   restart: always

  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN_EMAIL}
  #     PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASSWORD}
  #   ports:
  #     - "${PG_ADMIN_PORT}:8080"
  #   env_file:
  #     - .env
  #   restart: always

  # minio:
  #   image: quay.io/minio/minio
  #   container_name: minio
  #   environment:
  #     MINIO_ROOT_USER: ${MINIO_ADMIN_USER}
  #     MINIO_ROOT_PASSWORD: ${MINIO_ADMIN_PASSWORD}
  #   ports:
  #     - "${MINIO_API_PORT}:9000"
  #     - "${MINIO_WEB_CONSOLE_PORT}:9001"
  #   command: server /data --console-address ":9001"    
  #   env_file:
  #     - .env
  #   restart: always

  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: adminpass
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq
    env_file:
      - .env
    restart: always