version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.10.7-management
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: adminpass
    ports:
      - "5672:5672"    
      - "15672:15672"
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq  
    env_file:
      - .env 
    restart: always
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
  
  fastapi:
    build: .
    command: ["python", "main.py"]
    depends_on:
      rabbitmq:
        condition: service_healthy

  faststream:
    build: . 
    command: ["faststream", "run", "main:faststream_app"]
    depends_on:
      rabbitmq:
        condition: service_healthy

  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - RABBITMQ_URL=amqp://admin:adminpass@rabbitmq:5672
    depends_on:
      fastapi:
        condition: service_started
      faststream:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped
